FROM node:20-alpine

WORKDIR /app

COPY package.json ./
RUN npm install

COPY server.js seeder.js .sequelizerc ./
COPY src ./src
COPY migrations ./migrations

EXPOSE 5000

CMD ["npm", "run", "start:backend"]
